/**
 * src/shared/utils/harness/directive-templates.ts
 * Plantillas de texto de directivas para el arnés forgeAB.
 */

import type { DetectionResult } from './types.js';
import { getModelGuidelines } from './model-detector.js';

/**
 * Construye la cabecera e instrucciones centrales de forgeAB para cualquier asistente de IA.
 * @param result - Resultado de la detección de IDE y modelo
 * @returns Cadena con directivas SDD obligatorias
 */
export function buildCoreDirective(result: DetectionResult): string {
  const modelNotes = getModelGuidelines(result.model);
  return `# forgeAB AI Harness Directive
<!-- AUTOMATICALLY GENERATED BY FORGEAB HARNESS ADAPTER -->
<!-- DETECTED_IDE: ${result.ide} | DETECTED_MODEL: ${result.modelName} -->

## OBLIGACIÓN INELUDIBLE DEL ARNÉS
Operas bajo el arnés de desarrollo **forgeAB (OpenSpec Spec-Driven Development)**.
Está TERMINANTEMENTE PROHIBIDO escribir código de producción sin Delta Specs aprobadas y tests.

### Orden de Lectura Obligatorio al Iniciar Sesión:
1. \`utilities/agents/leader.md\` (Define tu rol como Leader de coordinación)
2. \`openspec/config.yaml\` (Contexto global de arquitectura)
3. \`openspec/specs/project-rules.md\` (Directrices maestras inviolables)
4. \`project-logs/current-dev.yaml\` (Estado activo y cambios en progreso)

### Reglas de Calidad y Anti-Monolito:
- Gestor de paquetes exclusivo: \`pnpm\`.
- Límite por archivo: Máximo 150 líneas de código.
- Límite por función: Máximo 30 líneas de código.
- Puertas de calidad: Todas las 7 Quality Gates deben pasar (\`pnpm quality-gate\`).
- Edición Quirúrgica Semántica: Preserva estrictamente el código circundante.

### Adaptación del Modelo Activo:
${modelNotes}
`;
}
