#!/usr/bin/env node
/**
 * scripts/harness-adapter.js
 * forgeAB Automated IDE & Model Detection and Root Directives Synchronization Engine
 */

import fs from 'node:fs';
import path from 'node:path';

const ROOT_DIR = process.cwd();

/**
 * Detecta la IDE activa basada en entorno y archivos
 */
function detectIde(env = process.env, cwd = ROOT_DIR) {
  if (env.ANTIGRAVITY_WORKSPACE || env.ANTIGRAVITY_IDE) {
    return { ide: 'antigravity', reason: 'Variable de entorno ANTIGRAVITY detectada' };
  }
  if (env.CURSOR_VERSION || env.CURSOR_TRACE_ID) {
    return { ide: 'cursor', reason: 'Variable de entorno CURSOR detectada' };
  }
  if (env.WINDSURF_VERSION) {
    return { ide: 'windsurf', reason: 'Variable de entorno WINDSURF detectada' };
  }
  if (env.CLAUDE_PROJECT_DIR || env.CLAUDE_CODE_ENTRY) {
    return { ide: 'claude-code', reason: 'Variable de entorno CLAUDE detectada' };
  }
  if (env.OPENCODE_VERSION) {
    return { ide: 'opencode', reason: 'Variable de entorno OPENCODE detectada' };
  }
  if (env.VSCODE_PID || env.TERM_PROGRAM === 'vscode') {
    return { ide: 'vscode', reason: 'Variable de entorno VSCODE detectada' };
  }
  if (fs.existsSync(path.join(cwd, '.antigravity'))) {
    return { ide: 'antigravity', reason: 'Directorio .antigravity/ presente' };
  }
  if (fs.existsSync(path.join(cwd, '.cursor')) || fs.existsSync(path.join(cwd, '.cursorrules'))) {
    return { ide: 'cursor', reason: 'Configuración de Cursor detectada' };
  }
  if (fs.existsSync(path.join(cwd, '.windsurf')) || fs.existsSync(path.join(cwd, '.windsurfrules'))) {
    return { ide: 'windsurf', reason: 'Configuración de Windsurf detectada' };
  }
  if (fs.existsSync(path.join(cwd, '.opencode'))) {
    return { ide: 'opencode', reason: 'Directorio .opencode/ presente' };
  }
  return { ide: 'generic', reason: 'Sin huella específica; perfil universal' };
}

/**
 * Detecta o infiere la familia de modelo
 */
function detectModel(env = process.env, fallback = 'Gemini 3.8 Flash') {
  const candidates = [env.AI_MODEL, env.MODEL, env.LLM_MODEL, env.GEMINI_MODEL, env.ANTHROPIC_MODEL, env.OPENAI_MODEL];
  for (const c of candidates) {
    if (c && c.trim()) {
      const lower = c.toLowerCase();
      if (lower.includes('gemini')) return { model: 'gemini', modelName: c.trim() };
      if (lower.includes('claude') || lower.includes('sonnet')) return { model: 'claude', modelName: c.trim() };
      if (lower.includes('gpt') || lower.includes('o1') || lower.includes('o3')) return { model: 'gpt', modelName: c.trim() };
      if (lower.includes('deepseek')) return { model: 'deepseek', modelName: c.trim() };
    }
  }
  return { model: 'gemini', modelName: fallback };
}

/**
 * Retorna las directivas para la IA
 */
function getDirectiveTemplate(ide, model, modelName) {
  return `# forgeAB AI Harness Directive
<!-- AUTOMATICALLY GENERATED BY FORGEAB HARNESS ADAPTER -->
<!-- DETECTED_IDE: ${ide} | DETECTED_MODEL: ${modelName} -->

## OBLIGACIÓN INELUDIBLE DEL ARNÉS
Operas bajo el arnés de desarrollo **forgeAB (OpenSpec Spec-Driven Development)**.
Está TERMINANTEMENTE PROHIBIDO escribir código de producción sin Delta Specs aprobadas y tests.

### Orden de Lectura Obligatorio al Iniciar Sesión:
1. \`utilities/agents/leader.md\` (Define tu rol como Leader de coordinación)
2. \`openspec/config.yaml\` (Contexto global de arquitectura)
3. \`openspec/specs/project-rules.md\` (Directrices maestras inviolables)
4. \`project-logs/current-dev.yaml\` (Estado activo y cambios en progreso)

### Reglas de Calidad y Anti-Monolito:
- Gestor de paquetes exclusivo: \`pnpm\`.
- Límite por archivo: Máximo 150 líneas de código.
- Límite por función: Máximo 30 líneas de código.
- Puertas de calidad: Todas las 7 Quality Gates deben pasar (\`pnpm quality-gate\`).
- Edición Quirúrgica Semántica: Preserva estrictamente el código circundante.

### Adaptación del Modelo Activo (${modelName}):
- Rol: Leader de forgeAB. Sigue estrictamente el ciclo Spec-Driven Development y no saltes verificaciones.
`;
}

/**
 * Ejecuta la sincronización
 */
export function runAdaptation(cwd = ROOT_DIR) {
  const ideInfo = detectIde(process.env, cwd);
  const modelInfo = detectModel(process.env);
  const content = getDirectiveTemplate(ideInfo.ide, modelInfo.model, modelInfo.modelName);

  const targets = [
    'GEMINI.md',
    'AGENTS.md',
    'CLAUDE.md',
    '.cursorrules',
    '.windsurfrules',
    path.join('.github', 'copilot-instructions.md'),
    path.join('.antigravity', 'context.md'),
    path.join('.opencode', 'instructions.md'),
  ];

  const written = [];
  for (const rel of targets) {
    const full = path.join(cwd, rel);
    const dir = path.dirname(full);
    if (!fs.existsSync(dir)) fs.mkdirSync(dir, { recursive: true });
    const cur = fs.existsSync(full) ? fs.readFileSync(full, 'utf-8') : null;
    if (cur !== content) {
      fs.writeFileSync(full, content, 'utf-8');
      written.push(rel);
    }
  }

  return { ide: ideInfo.ide, model: modelInfo.modelName, reason: ideInfo.reason, written };
}

// CLI Execution
if (process.argv[1] && process.argv[1].endsWith('harness-adapter.js')) {
  const result = runAdaptation();
  console.log(`\n  \x1b[36mforgeAB Harness Adapter\x1b[0m`);
  console.log(`  -------------------------------------------------------------`);
  console.log(`  IDE detectada:   \x1b[32m${result.ide}\x1b[0m (${result.reason})`);
  console.log(`  Modelo inferido: \x1b[32m${result.model}\x1b[0m`);
  if (result.written.length > 0) {
    console.log(`  Archivos raíz actualizados:`);
    result.written.forEach(f => console.log(`    - \x1b[34m${f}\x1b[0m`));
  } else {
    console.log(`  Archivos raíz ya se encontraban actualizados y sincronizados.`);
  }
  console.log(`  -------------------------------------------------------------\n`);
}
